# Generated by Django 6.0.4 on 2026-05-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_prof_alter_cursos_id_cursos_profe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='profe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='cursos.prof'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
